substitutions:
  device_id: haier_climate
  uart_id: ac_port 
  send_wifi: "true"

esphome:
  name: haier
  friendly_name: Haier AC
  name_add_mac_suffix: true

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

uart:
  baud_rate: 9600
  id: ${uart_id}  
  tx_pin: GPIO0
  rx_pin: GPIO1

<<: !include .haier-hon-base.yaml
