substitutions:
  device_name: "Dual UART Sniffer for Haier Project"
  device_id: uart_sniffer

esphome:
  name: ${device_id}
  comment: ${device_name}

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
api:
  reboot_timeout: 0s

ota:
  - platform: esphome

web_server:

logger:
  tx_buffer_size: 4096
  baud_rate: 0
  level: DEBUG

uart:
  - id: esp_board
    rx_pin: GPIO3
    baud_rate: 9600
    debug:
      direction: RX
      dummy_receiver: true
      sequence:
        - lambda: UARTDebug::log_hex(uart::UART_DIRECTION_RX, bytes, ' ');
  - id: haier_appliance
    rx_pin: GPIO16
    baud_rate: 9600
    debug:
      direction: RX
      dummy_receiver: true
      sequence:
        - lambda: UARTDebug::log_hex(uart::UART_DIRECTION_TX, bytes, ' ');
