esphome:
  name: haier

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG: y
    version: 5.3.1
    platform_version: 6.8.1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  baud_rate: 9600
  tx_pin: 12
  rx_pin: 13

logger:
  level: WARN

climate:
  - platform: haier
    protocol: hon
    name: Haier AC
