esphome:
  name: haier
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  baud_rate: 9600
  tx_pin: 18
  rx_pin: 19

logger:
  level: WARN

climate:
  - platform: haier
    name: Haier AC
